BROWSE_CHILDREN = 'BrowseDirectChildren'
BROWSE_METADATA = 'BrowseMetadata'
CID_SEARCH_ARTISTS = '0/My Music/Search/TrackArtists'
CID_SEARCH_ALBUMS = '0/My Music/Search/Albums'
CID_SEARCH_COMPOSERS = '0/My Music/Search/Composers'
CID_SEARCH_ALLTRACKS = '0/My Music/Search/AllTracks'
DEFAULT_PORT_WEBSERVICE = 47365
DELAY_REQUEST_FAILURE_LONG_POLLING = 60
DELAY_FAST_UPDATE_CHECKS = 0.1
PLAY_MODE_NORMAL = 'NORMAL'
PLAY_MODE_SHUFFLE = 'SHUFFLE'
PLAY_MODE_REPEAT_ONE = 'REPEAT_ONE'
PLAY_MODE_REPEAT_ALL = 'REPEAT_ALL'
PLAY_MODE_RANDOM = 'RANDOM'
PREFERRED_TIMEOUT_LONG_POLLING = 300
REQUIRED_METADATA = {
    "DIDL-Lite": {
        "item": {
            "upnp:class": "object.item.audioItem"
        }
    }
}
TRANSPORT_STATE_NO_MEDIA = "NO_MEDIA_PRESENT"
TRANSPORT_STATE_PAUSED = "PAUSED_PLAYBACK"
TRANSPORT_STATE_PLAYING = "PLAYING"
TRANSPORT_STATE_STOPPED = "STOPPED"
TRANSPORT_STATE_TRANSITIONING = "TRANSITIONING"
TIMEOUT_WEBSERVICE_ACTION = 5
TRIGGER_UPDATE_DEVICES = 'devices'
TRIGGER_UPDATE_HOST_INFO = 'host_info'
TRIGGER_UPDATE_SYSTEM_STATE = 'system_state'
TRIGGER_UPDATE_ZONE_CONFIG = 'zone_config'
TYPE_MEDIA_SERVER = 'urn:schemas-upnp-org:device:MediaServer:1'
TYPE_RAUMFELD_DEVICE = 'urn:schemas-raumfeld-com:device:RaumfeldDevice:1'
CONTENT_DIRECTORY = 'urn:schemas-upnp-org:service:ContentDirectory:1'
